"""
Official standards seed data (NGSS HS-PS and AP Chemistry CED).

STANDARDS_SEED is a flat list: each row has ``source`` (stored as ``framework`` in DB),
``category``, and ``is_core``. Lesson ↔ standard junction rows are in lesson_standards.py.
"""

from typing import TypedDict


class StandardSeedRow(TypedDict):
    code: str
    source: str
    title: str
    description: str | None
    category: str | None
    is_core: bool


STANDARDS_SEED: list[StandardSeedRow] = [
    # ── NGSS: High School Physical Sciences ───────────────────────────
    {
        "code": "HS-PS1-1",
        "source": "NGSS",
        "title": "Predict properties based on valence electrons",
        "description": "Use the periodic table as a model to predict the relative properties of elements based on the patterns of electrons in the outermost energy level of atoms.",
        "category": "Structure and Properties of Matter",
        "is_core": True,
    },
    {
        "code": "HS-PS1-2",
        "source": "NGSS",
        "title": "Explain simple chemical reactions",
        "description": "Construct and revise an explanation for the outcome of a simple chemical reaction based on the outermost electron states of atoms, trends in the periodic table, and knowledge of the patterns of chemical properties.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "HS-PS1-3",
        "source": "NGSS",
        "title": "Bulk scale structure and electrical forces",
        "description": "Plan and conduct an investigation to gather evidence to compare the structure of substances at the bulk scale to infer the strength of electrical forces between particles (IMFs).",
        "category": "Structure and Properties of Matter",
        "is_core": True,
    },
    {
        "code": "HS-PS1-4",
        "source": "NGSS",
        "title": "Total bond energy and chemical reactions",
        "description": "Develop a model to illustrate that the release or absorption of energy from a chemical reaction system depends upon the changes in total bond energy.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "HS-PS1-5",
        "source": "NGSS",
        "title": "Collision theory and reaction rates",
        "description": "Apply scientific principles and evidence to provide an explanation about the effects of changing the temperature or concentration of the reacting particles on the rate at which a reaction occurs.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "HS-PS1-6",
        "source": "NGSS",
        "title": "Le Chatelier's Principle and Equilibrium",
        "description": "Refine the design of a chemical system by specifying a change in conditions that would produce increased amounts of products at equilibrium.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "HS-PS1-7",
        "source": "NGSS",
        "title": "Conservation of atoms and mass (Stoichiometry)",
        "description": "Use mathematical representations to support the claim that atoms, and therefore mass, are conserved during a chemical reaction.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "HS-PS1-8",
        "source": "NGSS",
        "title": "Nuclear Processes",
        "description": "Develop models to illustrate the changes in the composition of the nucleus of the atom and the energy released during the processes of fission, fusion, and radioactive decay.",
        "category": "Nuclear Processes",
        "is_core": True,
    },
    {
        "code": "HS-PS3-4",
        "source": "NGSS",
        "title": "Thermodynamics and Heat Transfer",
        "description": "Plan and conduct an investigation to provide evidence that the transfer of thermal energy when two components of different temperature are combined within a closed system results in a more uniform energy distribution (Second Law of Thermodynamics).",
        "category": "Energy",
        "is_core": True,
    },
    # ── AP Chemistry CED (by unit / topic) ───────────────────────────
    # Unit 1 — Atomic Structure and Properties
    {
        "code": "AP-1.1",
        "source": "AP",
        "title": "Moles and Molar Mass",
        "description": "Calculate quantities of a substance or its relative number of particles using dimensional analysis and the mole concept.",
        "category": "Atomic Structure and Properties",
        "is_core": True,
    },
    {
        "code": "AP-1.2",
        "source": "AP",
        "title": "Mass Spectrometry of Elements",
        "description": "Explain the quantitative relationship between the mass spectrum of an element and the masses of the element's isotopes.",
        "category": "Atomic Structure and Properties",
        "is_core": True,
    },
    {
        "code": "AP-1.3",
        "source": "AP",
        "title": "Elemental Composition of Pure Substances",
        "description": "Explain the quantitative relationship between the elemental composition by mass and the empirical formula of a pure substance.",
        "category": "Atomic Structure and Properties",
        "is_core": True,
    },
    {
        "code": "AP-1.5",
        "source": "AP",
        "title": "Atomic Structure and Electron Configuration",
        "description": "Represent the electron configuration of an element or ions of an element using the Aufbau principle.",
        "category": "Atomic Structure and Properties",
        "is_core": True,
    },
    {
        "code": "AP-1.6",
        "source": "AP",
        "title": "Photoelectron Spectroscopy",
        "description": "Explain the relationship between the photoelectron spectrum of an atom or ion and the electron configuration of the species.",
        "category": "Atomic Structure and Properties",
        "is_core": True,
    },
    {
        "code": "AP-1.7",
        "source": "AP",
        "title": "Periodic Trends",
        "description": "Explain the relationship between trends in atomic properties of elements and atomic structure and periodicity.",
        "category": "Atomic Structure and Properties",
        "is_core": True,
    },
    # Unit 2 — Molecular and Ionic Compound Structure and Properties
    {
        "code": "AP-2.1",
        "source": "AP",
        "title": "Types of Chemical Bonds",
        "description": "Explain the relationship between the type of bonding and the solid properties based on electronegativity differences.",
        "category": "Molecular and Ionic Compound Structure",
        "is_core": True,
    },
    {
        "code": "AP-2.3",
        "source": "AP",
        "title": "Structure of Ionic Solids",
        "description": "Represent the ionic solid structure using particulate models that show maximizing attractions and minimizing repulsions.",
        "category": "Molecular and Ionic Compound Structure",
        "is_core": True,
    },
    {
        "code": "AP-2.5",
        "source": "AP",
        "title": "Lewis Diagrams",
        "description": "Represent a molecule with a Lewis diagram, showing bonding and nonbonding electron pairs.",
        "category": "Molecular and Ionic Compound Structure",
        "is_core": True,
    },
    {
        "code": "AP-2.6",
        "source": "AP",
        "title": "Resonance and Formal Charge",
        "description": "Represent a molecule with a Lewis diagram that accounts for resonance and calculates formal charge to determine the best structure.",
        "category": "Molecular and Ionic Compound Structure",
        "is_core": True,
    },
    {
        "code": "AP-2.7",
        "source": "AP",
        "title": "VSEPR and Bond Hybridization",
        "description": "Predict the geometry and hybridization (sp, sp2, sp3) of a central atom based on VSEPR theory.",
        "category": "Molecular and Ionic Compound Structure",
        "is_core": True,
    },
    # Unit 3 — Intermolecular Forces and Properties
    {
        "code": "AP-3.1",
        "source": "AP",
        "title": "Intermolecular Forces",
        "description": "Explain the relationship between the chemical structures of molecules and the relative strength of their intermolecular forces.",
        "category": "Intermolecular Forces and Properties",
        "is_core": True,
    },
    {
        "code": "AP-3.4",
        "source": "AP",
        "title": "Ideal Gas Law",
        "description": "Explain the relationship between the macroscopic properties of a sample of gas or mixture of gases using the ideal gas law.",
        "category": "Intermolecular Forces and Properties",
        "is_core": True,
    },
    {
        "code": "AP-3.8",
        "source": "AP",
        "title": "Representations of Solutions",
        "description": "Using particulate models for mixtures, represent interactions between components (solute and solvent).",
        "category": "Intermolecular Forces and Properties",
        "is_core": True,
    },
    {
        "code": "AP-3.13",
        "source": "AP",
        "title": "Beer-Lambert Law",
        "description": "Explain the amount of light absorbed by a solution of molecules or ions in relationship to the concentration, path length, and molar absorptivity.",
        "category": "Intermolecular Forces and Properties",
        "is_core": True,
    },
    # Unit 4 — Chemical Reactions
    {
        "code": "AP-4.2",
        "source": "AP",
        "title": "Net Ionic Equations",
        "description": "Represent changes in matter with a balanced net ionic equation.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "AP-4.5",
        "source": "AP",
        "title": "Stoichiometry",
        "description": "Explain changes in the amounts of reactants and products based on the balanced reaction equation for a chemical process.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "AP-4.6",
        "source": "AP",
        "title": "Introduction to Titration",
        "description": "Identify the equivalence point in a titration based on the amounts of the titrant and analyte.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    {
        "code": "AP-4.9",
        "source": "AP",
        "title": "Oxidation-Reduction (Redox) Reactions",
        "description": "Represent a redox reaction with a balanced equation and identify oxidation states.",
        "category": "Chemical Reactions",
        "is_core": True,
    },
    # Unit 5 — Kinetics
    {
        "code": "AP-5.1",
        "source": "AP",
        "title": "Reaction Rates",
        "description": "Explain the relationship between the rate of a chemical reaction and experimental parameters.",
        "category": "Kinetics",
        "is_core": True,
    },
    {
        "code": "AP-5.2",
        "source": "AP",
        "title": "Introduction to Rate Law",
        "description": "Identify the rate law expression of a chemical reaction using data that show how the concentrations of reactants affect the rate.",
        "category": "Kinetics",
        "is_core": True,
    },
    {
        "code": "AP-5.3",
        "source": "AP",
        "title": "Concentration Changes Over Time",
        "description": "Identify the rate law expression of a chemical reaction using data that show how the concentration of a reactant changes over time (Integrated Rate Laws).",
        "category": "Kinetics",
        "is_core": True,
    },
    {
        "code": "AP-5.5",
        "source": "AP",
        "title": "Collision Model",
        "description": "Explain the relationship between the rate of an elementary reaction and the frequency, energy, and orientation of molecular collisions.",
        "category": "Kinetics",
        "is_core": True,
    },
    {
        "code": "AP-5.8",
        "source": "AP",
        "title": "Reaction Mechanism and Rate Law",
        "description": "Identify the rate law for a reaction from a mechanism in which the first step is rate determining.",
        "category": "Kinetics",
        "is_core": True,
    },
    {
        "code": "AP-5.11",
        "source": "AP",
        "title": "Catalysis",
        "description": "Explain the relationship between the effect of a catalyst on a reaction and changes in the reaction mechanism.",
        "category": "Kinetics",
        "is_core": True,
    },
    # Unit 6 — Thermodynamics
    {
        "code": "AP-6.1",
        "source": "AP",
        "title": "Endothermic and Exothermic Processes",
        "description": "Explain the relationship between experimental observations and energy changes associated with a chemical or physical transformation.",
        "category": "Thermodynamics",
        "is_core": True,
    },
    {
        "code": "AP-6.4",
        "source": "AP",
        "title": "Heat Capacity and Calorimetry",
        "description": "Calculate the heat q absorbed or released by a system undergoing heating/cooling based on the amount of the substance, heat capacity, and change in temperature.",
        "category": "Thermodynamics",
        "is_core": True,
    },
    {
        "code": "AP-6.8",
        "source": "AP",
        "title": "Enthalpy of Formation",
        "description": "Calculate the enthalpy change for a chemical or physical process based on the standard enthalpies of formation.",
        "category": "Thermodynamics",
        "is_core": True,
    },
    {
        "code": "AP-6.9",
        "source": "AP",
        "title": "Hess's Law",
        "description": "Represent a chemical or physical process as a sequence of steps; and calculate the enthalpy change using Hess's Law.",
        "category": "Thermodynamics",
        "is_core": True,
    },
    # Unit 7 — Equilibrium
    {
        "code": "AP-7.2",
        "source": "AP",
        "title": "Direction of Reversible Reactions",
        "description": "Explain the relationship between the direction in which a reversible reaction proceeds and the relative rates of the forward and reverse reactions.",
        "category": "Equilibrium",
        "is_core": True,
    },
    {
        "code": "AP-7.4",
        "source": "AP",
        "title": "Calculating the Equilibrium Constant",
        "description": "Calculate the value of an equilibrium constant, K, from concentration data.",
        "category": "Equilibrium",
        "is_core": True,
    },
    {
        "code": "AP-7.9",
        "source": "AP",
        "title": "Introduction to Le Chatelier's Principle",
        "description": "Identify the response of a system at equilibrium to an external stress, using Le Chatelier's principle.",
        "category": "Equilibrium",
        "is_core": True,
    },
    {
        "code": "AP-7.11",
        "source": "AP",
        "title": "Introduction to Solubility Equilibria",
        "description": "Calculate the solubility of a salt based on the value of Ksp for the salt.",
        "category": "Equilibrium",
        "is_core": True,
    },
    # Unit 8 — Acids and Bases
    {
        "code": "AP-8.1",
        "source": "AP",
        "title": "Introduction to Acids and Bases",
        "description": "Identify acids and bases and explain their behavior in aqueous solutions based on Arrhenius, Brønsted-Lowry, and Lewis definitions.",
        "category": "Acids and Bases",
        "is_core": True,
    },
    {
        "code": "AP-8.2",
        "source": "AP",
        "title": "pH and pOH of Strong Acids and Bases",
        "description": "Calculate pH and pOH based on concentrations of particulate species in a solution of a strong acid or a strong base.",
        "category": "Acids and Bases",
        "is_core": True,
    },
    {
        "code": "AP-8.3",
        "source": "AP",
        "title": "Weak Acid and Base Equilibria",
        "description": "Calculate pH and pOH based on concentrations of particulate species in a solution of a weak acid or a weak base (using Ka and Kb).",
        "category": "Acids and Bases",
        "is_core": True,
    },
    {
        "code": "AP-8.5",
        "source": "AP",
        "title": "Acid-Base Titrations",
        "description": "Explain results from the titration of a mono- or polyprotic acid or base solution, in relation to the properties of the solution and its components.",
        "category": "Acids and Bases",
        "is_core": True,
    },
    {
        "code": "AP-8.8",
        "source": "AP",
        "title": "Properties of Buffers",
        "description": "Explain the relationship between the ability of a buffer to stabilize pH and the reactions that occur when an acid or a base is added to a buffered solution.",
        "category": "Acids and Bases",
        "is_core": True,
    },
    # Unit 9 — Applications of Thermodynamics
    {
        "code": "AP-9.1",
        "source": "AP",
        "title": "Introduction to Entropy",
        "description": "Identify the sign and relative magnitude of the entropy change associated with chemical or physical processes.",
        "category": "Applications of Thermodynamics",
        "is_core": True,
    },
    {
        "code": "AP-9.3",
        "source": "AP",
        "title": "Gibbs Free Energy and Thermodynamic Favorability",
        "description": "Explain whether a physical or chemical process is thermodynamically favored based on an evaluation of ΔG°.",
        "category": "Applications of Thermodynamics",
        "is_core": True,
    },
    {
        "code": "AP-9.5",
        "source": "AP",
        "title": "Free Energy and Equilibrium",
        "description": "Explain whether a physical or chemical process is thermodynamically favored based on an evaluation of ΔG° and K.",
        "category": "Applications of Thermodynamics",
        "is_core": True,
    },
    {
        "code": "AP-9.7",
        "source": "AP",
        "title": "Galvanic (Voltaic) and Electrolytic Cells",
        "description": "Explain the relationship between the physical components of a galvanic or electrolytic cell and the overall operational principles of the cell.",
        "category": "Applications of Thermodynamics",
        "is_core": True,
    },
    {
        "code": "AP-9.8",
        "source": "AP",
        "title": "Cell Potential and Free Energy",
        "description": "Explain the relationship between the standard cell potential of a galvanic or electrolytic cell and the thermodynamic favorability of the overall redox reaction (ΔG° = -nFE°).",
        "category": "Applications of Thermodynamics",
        "is_core": True,
    },
]
