"""full_schema

Revision ID: 0258e0f4835d
Revises: 
Create Date: 2026-03-28 22:12:36.136251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0258e0f4835d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exit_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_tickets_class_id'), 'exit_tickets', ['class_id'], unique=False)
    op.create_table('few_shot_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=True),
    sa.Column('variant_index', sa.Integer(), server_default='1', nullable=False),
    sa.Column('example_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_few_shot_lookup', 'few_shot_examples', ['unit_id', 'lesson_index', 'difficulty', 'level', 'strategy', 'variant_index'], unique=True)
    op.create_table('generation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.String(length=100), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('execution_time_s', sa.Float(), nullable=False),
    sa.Column('problem_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gen_logs_prompt_version', 'generation_logs', ['prompt_version'], unique=False)
    op.create_index('ix_gen_logs_provider_model', 'generation_logs', ['provider', 'model_name'], unique=False)
    op.create_index('ix_gen_logs_unit_lesson', 'generation_logs', ['unit_id', 'lesson_index'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('lesson_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'unit_id', 'lesson_index')
    )
    op.create_index('ix_lesson_progress_user', 'lesson_progress', ['user_id'], unique=False)
    op.create_index('ix_lesson_progress_user_unit', 'lesson_progress', ['user_id', 'unit_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('key_equations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('misconceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blueprint', sa.String(length=20), nullable=False),
    sa.Column('required_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_ap_only', sa.Boolean(), nullable=False),
    sa.Column('extension_of', sa.String(length=100), nullable=True),
    sa.Column('has_simulation', sa.Boolean(), nullable=False),
    sa.Column('reference_card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_lessons_index', 'lessons', ['lesson_index'], unique=False)
    op.create_table('misconception_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=False),
    sa.Column('error_subcategory', sa.String(length=100), nullable=True),
    sa.Column('misconception_tag', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_misconception_class', 'misconception_logs', ['class_id'], unique=False)
    op.create_index('ix_misconception_unit', 'misconception_logs', ['unit_id', 'lesson_index'], unique=False)
    op.create_index('ix_misconception_user', 'misconception_logs', ['user_id'], unique=False)
    op.create_table('problem_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('step_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_user_level', 'problem_attempts', ['user_id', 'level'], unique=False)
    op.create_index('ix_attempts_user_unit', 'problem_attempts', ['user_id', 'unit_id', 'lesson_index'], unique=False)
    op.create_index(op.f('ix_problem_attempts_class_id'), 'problem_attempts', ['class_id'], unique=False)
    op.create_index(op.f('ix_problem_attempts_user_id'), 'problem_attempts', ['user_id'], unique=False)
    op.create_table('problem_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('context_tag', sa.String(length=50), nullable=True),
    sa.Column('problem_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_problem_cache_key', 'problem_cache', ['unit_id', 'lesson_index', 'difficulty', 'level', 'context_tag'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('skill_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.Column('current_difficulty', sa.String(length=20), nullable=False),
    sa.Column('level3_unlocked', sa.Boolean(), nullable=False),
    sa.Column('level3_unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_id', 'lesson_index', name='uq_mastery_user_lesson')
    )
    op.create_index('ix_mastery_user', 'skill_mastery', ['user_id'], unique=False)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('thinking_tracker_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=100), nullable=False),
    sa.Column('step_label', sa.String(length=100), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('student_input', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('reasoning_pattern', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thinking_tracker_logs_attempt_id'), 'thinking_tracker_logs', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_thinking_tracker_logs_user_id'), 'thinking_tracker_logs', ['user_id'], unique=False)
    op.create_index('ix_thinking_user_unit', 'thinking_tracker_logs', ['user_id', 'unit_id', 'lesson_index'], unique=False)
    op.create_table('user_lesson_playlists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('problems', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'unit_id', 'lesson_index', 'level', 'difficulty')
    )
    op.create_index('ix_playlist_user_unit', 'user_lesson_playlists', ['user_id', 'unit_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('exit_ticket_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exit_ticket_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exit_ticket_id'], ['exit_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_ticket_responses_exit_ticket_id'), 'exit_ticket_responses', ['exit_ticket_id'], unique=False)
    op.create_index(op.f('ix_exit_ticket_responses_student_id'), 'exit_ticket_responses', ['student_id'], unique=False)
    op.create_table('lesson_standards',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'standard_id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'sort_order', name='uq_phase_course_order')
    )
    op.create_index(op.f('ix_phases_course_id'), 'phases', ['course_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_profiles_role', 'user_profiles', ['role'], unique=False)
    op.create_table('student_interests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.create_table('units',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('gradient', sa.String(length=200), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('order_within_phase', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_coming_soon', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_units_grade_course', 'units', ['grade_id', 'course_id'], unique=False)
    op.create_index('ix_units_phase', 'units', ['phase_id'], unique=False)
    op.create_index(op.f('ix_units_phase_id'), 'units', ['phase_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_classrooms_teacher_id'), 'classrooms', ['teacher_id'], unique=False)
    op.create_table('curriculum_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_documents_lesson_id'), 'curriculum_documents', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_curriculum_documents_unit_id'), 'curriculum_documents', ['unit_id'], unique=False)
    op.create_table('unit_lessons',
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lesson_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'lesson_id')
    )
    op.create_index('ix_unit_lessons_unit', 'unit_lessons', ['unit_id'], unique=False)
    op.create_table('classroom_curriculum_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('custom_order', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'unit_id', name='uq_cco_classroom_unit')
    )
    op.create_index('ix_cco_classroom', 'classroom_curriculum_overrides', ['classroom_id'], unique=False)
    op.create_index('ix_cco_unit', 'classroom_curriculum_overrides', ['unit_id'], unique=False)
    op.create_table('classroom_students',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classroom_id', 'student_id')
    )
    op.create_index('ix_classroom_students_student', 'classroom_students', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_students_student', table_name='classroom_students')
    op.drop_table('classroom_students')
    op.drop_index('ix_cco_unit', table_name='classroom_curriculum_overrides')
    op.drop_index('ix_cco_classroom', table_name='classroom_curriculum_overrides')
    op.drop_table('classroom_curriculum_overrides')
    op.drop_index('ix_unit_lessons_unit', table_name='unit_lessons')
    op.drop_table('unit_lessons')
    op.drop_index(op.f('ix_curriculum_documents_unit_id'), table_name='curriculum_documents')
    op.drop_index(op.f('ix_curriculum_documents_lesson_id'), table_name='curriculum_documents')
    op.drop_table('curriculum_documents')
    op.drop_index(op.f('ix_classrooms_teacher_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_units_phase_id'), table_name='units')
    op.drop_index('ix_units_phase', table_name='units')
    op.drop_index('ix_units_grade_course', table_name='units')
    op.drop_table('units')
    op.drop_table('student_interests')
    op.drop_index('ix_user_profiles_role', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_phases_course_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_table('lesson_standards')
    op.drop_index(op.f('ix_exit_ticket_responses_student_id'), table_name='exit_ticket_responses')
    op.drop_index(op.f('ix_exit_ticket_responses_exit_ticket_id'), table_name='exit_ticket_responses')
    op.drop_table('exit_ticket_responses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_playlist_user_unit', table_name='user_lesson_playlists')
    op.drop_table('user_lesson_playlists')
    op.drop_index('ix_thinking_user_unit', table_name='thinking_tracker_logs')
    op.drop_index(op.f('ix_thinking_tracker_logs_user_id'), table_name='thinking_tracker_logs')
    op.drop_index(op.f('ix_thinking_tracker_logs_attempt_id'), table_name='thinking_tracker_logs')
    op.drop_table('thinking_tracker_logs')
    op.drop_table('standards')
    op.drop_index('ix_mastery_user', table_name='skill_mastery')
    op.drop_table('skill_mastery')
    op.drop_table('prompt_versions')
    op.drop_index('ix_problem_cache_key', table_name='problem_cache')
    op.drop_table('problem_cache')
    op.drop_index(op.f('ix_problem_attempts_user_id'), table_name='problem_attempts')
    op.drop_index(op.f('ix_problem_attempts_class_id'), table_name='problem_attempts')
    op.drop_index('ix_attempts_user_unit', table_name='problem_attempts')
    op.drop_index('ix_attempts_user_level', table_name='problem_attempts')
    op.drop_table('problem_attempts')
    op.drop_index('ix_misconception_user', table_name='misconception_logs')
    op.drop_index('ix_misconception_unit', table_name='misconception_logs')
    op.drop_index('ix_misconception_class', table_name='misconception_logs')
    op.drop_table('misconception_logs')
    op.drop_index('ix_lessons_index', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_lesson_progress_user_unit', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_user', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_table('interests')
    op.drop_table('grades')
    op.drop_index('ix_gen_logs_unit_lesson', table_name='generation_logs')
    op.drop_index('ix_gen_logs_provider_model', table_name='generation_logs')
    op.drop_index('ix_gen_logs_prompt_version', table_name='generation_logs')
    op.drop_table('generation_logs')
    op.drop_index('ix_few_shot_lookup', table_name='few_shot_examples')
    op.drop_table('few_shot_examples')
    op.drop_index(op.f('ix_exit_tickets_class_id'), table_name='exit_tickets')
    op.drop_table('exit_tickets')
    op.drop_table('courses')
    # ### end Alembic commands ###
