"""exit_ticket_published_at

Revision ID: c4732611e81f
Revises: 20260405_calc_enabled
Create Date: 2026-04-06 00:36:13.558392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4732611e81f'
down_revision: Union[str, None] = '20260405_calc_enabled'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exit_tickets', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_exit_tickets_published_at'), 'exit_tickets', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exit_tickets_published_at'), table_name='exit_tickets')
    op.drop_column('exit_tickets', 'published_at')
    # ### end Alembic commands ###
